															-- 22.08.2020 - 7:01PM
						-- CSDL: HE THONG BAN HANG QUA MANG
DROP DATABASE dbQLBanHangQuaMang
GO
CREATE DATABASE dbQLBanHangQuaMang

GO
use dbQLBanHangQuaMang

GO
CREATE TABLE NHAN_VIEN 
(
	MaNV VARCHAR(5) PRIMARY KEY, 
	TenNV NVARCHAR(50), 
	DiaChi NVARCHAR(50), 
	SDT VARCHAR(12), 
	ChucVu NVARCHAR(50),
	Password VARCHAR(50)
)

GO
CREATE TABLE NHA_CUNG_CAP 
(
	MaNCC VARCHAR(5) PRIMARY KEY, 
	TenNCC NVARCHAR(50), 
	DiaChi NVARCHAR(50), 
	SDT VARCHAR(12)
)

GO
CREATE TABLE THONG_KE_MAT_HANG 
(
	MaThongKe VARCHAR(5) PRIMARY KEY, 
	NgayLap DATE, 
	NVLapTK VARCHAR(5)
)

GO
CREATE TABLE CT_THONG_KE_MH 
(
	MaThongKe VARCHAR(5), 
	MaMH VARCHAR(5), 
	SLDaBan INT, 
	SLTon INT,
	PRIMARY KEY (MaThongKe, MaMH)
)

GO
CREATE TABLE DON_TRA_HANG 
(
	MaDTH VARCHAR(5) PRIMARY KEY,
	NgayLap DATE,
	NVLapDon VARCHAR(5), 
	MaNCC VARCHAR(5)
)

GO
CREATE TABLE CT_DON_TRA_HANG 
(
	MaDTH VARCHAR(5), 
	MaMH VARCHAR(5), 
	SoLuong INT, 
	LyDoTra INT,
	PRIMARY KEY (MaDTH, MaMH)
)

GO
CREATE TABLE MAT_HANG 
(
	MaMH VARCHAR(5) PRIMARY KEY, 
	TenMH NVARCHAR(50), 
	GiaTien FLOAT, 
	SLTon INT, 
	HinhAnh NVARCHAR(500),
	MoTa NVARCHAR(500),
	LoaiHang VARCHAR(5)
)

GO
CREATE TABLE LOAI_HANG 
(
	MaLH VARCHAR(5) PRIMARY KEY, 
	TenLH NVARCHAR(50),
	NVQuanLy VARCHAR(5)
)

GO
CREATE TABLE DON_NHAP_HANG 
(
	MaDNH VARCHAR(5) PRIMARY KEY, 
	NgayNhap DATE, 
	LyDoNhapHang NVARCHAR(100), 
	TongSL INT, 
	NVNhapHang VARCHAR(5), 
	QuanLyXacNhan VARCHAR(5), 
	MaNCC VARCHAR(5)
)

GO
CREATE TABLE CT_DNH 
(
	MaDNH VARCHAR(5), 
	MaMH VARCHAR(5), 
	SoLuong INT,
	PRIMARY KEY (MaDNH, MaMH)
)

GO
CREATE TABLE HOA_DON 
(
	MaHD VARCHAR(5) PRIMARY KEY, 
	NgayLap DATE, 
	TongTien FLOAT, 
	HinhThucTT NVARCHAR(20), 
	NVLapHD VARCHAR(5), 
	NVGiaoHang VARCHAR(5), 
	ThuQuyXacNhan VARCHAR(5), 
	MaKH VARCHAR(5)
)

GO
CREATE TABLE CT_HOA_DON 
(
	MaHD VARCHAR(5),
	MaMH VARCHAR(5), 
	DonGiaBan FLOAT, 
	SoLuong INT,
	PRIMARY KEY (MaHD, MaMH)
)

GO
CREATE TABLE KHACH_HANG 
(
	MaKH VARCHAR(5) PRIMARY KEY, 
	TenKH NVARCHAR(50), 
	Email VARCHAR(30), 
	DiaChi NVARCHAR(50), 
	SDT VARCHAR(12),
	Username VARCHAR(30),
	Password VARCHAR(30)
)

GO
CREATE TABLE THE_NGAN_HANG 
(
	MaThe VARCHAR(30) PRIMARY KEY, 
	TenNganHang NVARCHAR(30), 
	MaKH VARCHAR(5)
)

GO
CREATE TABLE HDTT_QUA_THE 
(
	MaHDTT VARCHAR(5) PRIMARY KEY, 
	NgayTTQuaThe DATE, 
	MaThe VARCHAR(30), 
	MaHD VARCHAR(5), 
	ThuQuyXacNhan VARCHAR(5)
)

GO
CREATE TABLE PHIEU_TRA_HANG 
(
	MaPhieu VARCHAR(5) PRIMARY KEY, 
	NgayLap DATE,
	MaHD VARCHAR(5),
	NVLap VARCHAR(5)
)

GO
CREATE TABLE CT_PTH 
(
	MaPhieu VARCHAR(5), 
	MaMH VARCHAR(5), 
	SoLuong INT, 
	LyDo NVARCHAR(100),
	PRIMARY KEY (MaPhieu, MaMH)
)

GO
CREATE TABLE TIN_QUANG_CAO 
(
	MaTin VARCHAR(5) PRIMARY KEY, 
	NgayLap DATE, 
	NoiDung NVARCHAR(200), 
	NVDangTin VARCHAR(5)
)

GO
CREATE TABLE LICH_SU_TIN_QC_KH 
(
	MaTin VARCHAR(5), 
	MaKH VARCHAR(5), 
	NgayGui DATE,
	PRIMARY KEY (MaTin, MaKH)
)

GO
CREATE TABLE DOI_TAC_QUANG_CAO 
(
	MaDoiTac VARCHAR(5) PRIMARY KEY, 
	TenDoiTac NVARCHAR(100), 
	DiaChi NVARCHAR(50), 
	SDT VARCHAR(12), 
	DanhGia NVARCHAR(100),
	SoLanGiaHan INT
)

GO
CREATE TABLE LICH_SU_TIN_QC_DOI_TAC 
(
	MaTin VARCHAR(5), 
	MaDoiTac VARCHAR(5), 
	NgayKyHD DATE, 
	ThoiGianQC INT, --SO LUONG NGAY 
	ThongTinViTriDang NVARCHAR(100),
	PRIMARY KEY (MaTin, MaDoiTac)
)

GO
CREATE TABLE THONG_KE_COMMENT 
(
	STT INT PRIMARY KEY, 
	NoiDung NVARCHAR(200), 
	LoaiCMT NVARCHAR(20), 
	MaKH VARCHAR(5), 
	NVThongKe VARCHAR(5)
)

GO
CREATE TABLE LICH_SU_TANG_QUA 
(
	SoTT INT PRIMARY KEY, 
	NgayTang DATE, 
	LyDo NVARCHAR(100), 
	QuaTang NVARCHAR(50), 
	NVLapLichSu VARCHAR(5), 
	MaKH VARCHAR(5)
)
GO
----------------------------
-- Create FKs for Tables:

-- 1. THONG_KE_MAT_HANG(NVLapTK) -> NHAN_VIEN(MaNV)
GO
ALTER TABLE THONG_KE_MAT_HANG
ADD CONSTRAINT FK_TKMH_NVLapTK
FOREIGN KEY (NVLapTK)
REFERENCES NHAN_VIEN(MaNV)

-- 2. CT_THONG_KE_MH(MaThongKe) -> THONG_KE_MAT_HANG(MaThongKe)
GO
ALTER TABLE CT_THONG_KE_MH
ADD CONSTRAINT FK_CTTKMH_TKMH
FOREIGN KEY (MaThongKe)
REFERENCES THONG_KE_MAT_HANG(MaThongKe)

-- 3. CT_THONG_KE_MH(MaMH) -> MAT_HANG(MaMH)
GO
ALTER TABLE CT_THONG_KE_MH
ADD CONSTRAINT FK_CTTKMH_MH
FOREIGN KEY (MaMH)
REFERENCES MAT_HANG(MaMH)

-- 4. DON_TRA_HANG(NVLapDon) -> NHAN_VIEN(MaNV)
GO
ALTER TABLE DON_TRA_HANG
ADD CONSTRAINT FK_DTH_NVLapDon
FOREIGN KEY (NVLapDon)
REFERENCES NHAN_VIEN(MaNV)

-- 5. DON_TRA_HANG(MaNCC) -> NHA_CUNG_CAP(MaNCC)
GO
ALTER TABLE DON_TRA_HANG
ADD CONSTRAINT FK_DTH_NCC
FOREIGN KEY (MaNCC)
REFERENCES NHA_CUNG_CAP(MaNCC)

-- 6. CT_DON_TRA_HANG(MaDTH) -> DON_TRA_HANG(MaDTH)
GO
ALTER TABLE CT_DON_TRA_HANG
ADD CONSTRAINT FK_CTDTH_DTH
FOREIGN KEY (MaDTH)
REFERENCES DON_TRA_HANG(MaDTH)

-- 7. CT_DON_TRA_HANG(MaMH) -> MAT_HANG(MaMH)
GO
ALTER TABLE CT_DON_TRA_HANG
ADD CONSTRAINT FK_CTDTH_MH
FOREIGN KEY (MaMH)
REFERENCES MAT_HANG(MaMH)

-- 8. MAT_HANG(LoaiHang) -> LOAI_HANG(MaLH)
GO
ALTER TABLE MAT_HANG
ADD CONSTRAINT FK_MH_LoaiMH
FOREIGN KEY (LoaiHang)
REFERENCES LOAI_HANG(MaLH)

-- 9. LOAI_HANG(NVQuanLy) -> NHAN_VIEN(MaNV)
GO
ALTER TABLE LOAI_HANG
ADD CONSTRAINT FK_LoaiMH_NVQLy
FOREIGN KEY (NVQuanLy)
REFERENCES NHAN_VIEN(MaNV)

-- 10. DON_NHAP_HANG(NVNhapHang) -> NHAN_VIEN(MaNV)
GO
ALTER TABLE DON_NHAP_HANG
ADD CONSTRAINT FK_DNH_NVNhapHang
FOREIGN KEY (NVNhapHang)
REFERENCES NHAN_VIEN(MaNV)

-- 11. DON_NHAP_HANG(QuanLyXacNhan) -> NHAN_VIEN(MaNV)
GO
ALTER TABLE DON_NHAP_HANG
ADD CONSTRAINT FK_DNH_QLXacNhan
FOREIGN KEY (QuanLyXacNhan)
REFERENCES NHAN_VIEN(MaNV)

-- 12. DON_NHAP_HANG(MaNCC) -> NHA_CUNG_CAP(MaNCC)
GO
ALTER TABLE DON_NHAP_HANG
ADD CONSTRAINT FK_DNH_NCC
FOREIGN KEY (MaNCC)
REFERENCES NHA_CUNG_CAP(MaNCC)

-- 13. CT_DNH(MaDNH) -> DON_NHAP_HANG(MaDNH)
GO
ALTER TABLE CT_DNH
ADD CONSTRAINT FK_CTDNH_DNH
FOREIGN KEY (MaDNH)
REFERENCES DON_NHAP_HANG(MaDNH)

-- 14. CT_DNH(MaMH) -> MAT_HANG(MaMH)
GO
ALTER TABLE CT_DNH
ADD CONSTRAINT FK_CTDNH_MH
FOREIGN KEY (MaMH)
REFERENCES MAT_HANG(MaMH)

-- 15. HOA_DON(NVLapHD) -> NHAN_VIEN(MaNV)
GO
ALTER TABLE HOA_DON
ADD CONSTRAINT FK_HD_NVLapHD
FOREIGN KEY (NVLapHD)
REFERENCES NHAN_VIEN(MaNV)

-- 16. HOA_DON(NVGiaoHang) -> NHAN_VIEN(MaNV)
GO
ALTER TABLE HOA_DON
ADD CONSTRAINT FK_HD_NVGiaoHang
FOREIGN KEY (NVGiaoHang)
REFERENCES NHAN_VIEN(MaNV)

-- 17. HOA_DON(ThuQuyXacNhan) -> NHAN_VIEN(MaNV)
GO
ALTER TABLE HOA_DON
ADD CONSTRAINT FK_HD_ThuQuyXacNhan
FOREIGN KEY (ThuQuyXacNhan)
REFERENCES NHAN_VIEN(MaNV)

-- 18. HOA_DON(MaKH) -> KHACH_HANG(MaKH)
GO
ALTER TABLE HOA_DON
ADD CONSTRAINT FK_HD_KhachHang
FOREIGN KEY (MaKH)
REFERENCES KHACH_HANG(MaKH)

-- 19. CT_HOA_DON(MaHD) -> HOA_DON(MaHD)
GO
ALTER TABLE CT_HOA_DON
ADD CONSTRAINT FK_CTHD_HoaDon
FOREIGN KEY (MaHD)
REFERENCES HOA_DON(MaHD)

-- 20. CT_HOA_DON(MaMH) -> MAT_HANG(MaMH)
GO
ALTER TABLE CT_HOA_DON
ADD CONSTRAINT FK_CTHD_MatHang
FOREIGN KEY (MaMH)
REFERENCES MAT_HANG(MaMH)

-- 21. THE_NGAN_HANG(MaKH) -> KHACH_HANG(MaKH)
GO
ALTER TABLE THE_NGAN_HANG
ADD CONSTRAINT FK_TheNH_KhachHang
FOREIGN KEY (MaKH)
REFERENCES KHACH_HANG(MaKH)

-- 22. HDTT_QUA_THE(MaThe) -> THE_NGAN_HANG(MaThe)
GO
ALTER TABLE HDTT_QUA_THE
ADD CONSTRAINT FK_HDTTQuaThe_TheNH
FOREIGN KEY (MaThe)
REFERENCES THE_NGAN_HANG(MaThe)

-- 23. HDTT_QUA_THE(MaHD) -> HOA_DON(MaHD)
GO
ALTER TABLE HDTT_QUA_THE
ADD CONSTRAINT FK_HDTTQuaThe_HoaDon
FOREIGN KEY (MaHD)
REFERENCES HOA_DON(MaHD)

-- 24. HDTT_QUA_THE(ThuQuyXacNhan) -> NHAN_VIEN(MaNV)
GO
ALTER TABLE HDTT_QUA_THE
ADD CONSTRAINT FK_HDTTQuaThe_NVXacNhan
FOREIGN KEY (ThuQuyXacNhan)
REFERENCES NHAN_VIEN(MaNV)

-- 25. PHIEU_TRA_HANG(MaHD) -> HOA_DON(MaHD)
GO
ALTER TABLE PHIEU_TRA_HANG
ADD CONSTRAINT FK_PTH_HoaDon
FOREIGN KEY (MaHD)
REFERENCES HOA_DON(MaHD)

-- 26. PHIEU_TRA_HANG(NVLap) -> NHAN_VIEN(MaNV)
GO
ALTER TABLE PHIEU_TRA_HANG
ADD CONSTRAINT FK_PTH_NVLap
FOREIGN KEY (NVLap)
REFERENCES NHAN_VIEN(MaNV)

-- 27. CT_PTH(MaPhieu) -> PHIEU_TRA_HANG(MaPhieu)
GO
ALTER TABLE CT_PTH
ADD CONSTRAINT FK_CTPTH_PTH
FOREIGN KEY (MaPhieu)
REFERENCES PHIEU_TRA_HANG(MaPhieu)

-- 28. CT_PTH(MaMH) -> MAT_HANG(MaMH)
GO
ALTER TABLE CT_PTH
ADD CONSTRAINT FK_CTPTH_MatHang
FOREIGN KEY (MaMH)
REFERENCES MAT_HANG(MaMH)

-- 29. TIN_QUANG_CAO(NVDangTin) -> NHAN_VIEN(MaNV)
GO
ALTER TABLE TIN_QUANG_CAO
ADD CONSTRAINT FK_TinQuangCao_NhanVien
FOREIGN KEY (NVDangTin)
REFERENCES NHAN_VIEN(MaNV)

-- 30. LICH_SU_TIN_QC_KH(MaTin) -> TIN_QUANG_CAO(MaTin)
GO
ALTER TABLE LICH_SU_TIN_QC_KH
ADD CONSTRAINT FK_LichSuTinQCKH_TinQC
FOREIGN KEY (MaTin)
REFERENCES TIN_QUANG_CAO(MaTin)

-- 31. LICH_SU_TIN_QC_KH(MaKH) -> KHACH_HANG(MaKH)
GO
ALTER TABLE LICH_SU_TIN_QC_KH
ADD CONSTRAINT FK_LichSuTinQCKH_KhachHang
FOREIGN KEY (MaKH)
REFERENCES KHACH_HANG(MaKH)

-- 32. LICH_SU_TIN_QC_DOI_TAC(MaTin) -> TIN_QUANG_CAO(MaTin)
GO
ALTER TABLE LICH_SU_TIN_QC_DOI_TAC
ADD CONSTRAINT FK_LichSuTinQCDT_TinQC
FOREIGN KEY (MaTin)
REFERENCES TIN_QUANG_CAO(MaTin)

-- 33. LICH_SU_TIN_QC_DOI_TAC(MaDoiTac) -> DOI_TAC_QUANG_CAO(MaDoiTac)
GO
ALTER TABLE LICH_SU_TIN_QC_DOI_TAC
ADD CONSTRAINT FK_LichSuTinQCDT_DTQC
FOREIGN KEY (MaDoiTac)
REFERENCES DOI_TAC_QUANG_CAO(MaDoiTac)

-- 34. THONG_KE_COMMENT(MaKH) -> KHACH_HANG(MaKH)
GO
ALTER TABLE THONG_KE_COMMENT
ADD CONSTRAINT FK_ThongKeCMT_KhachHang
FOREIGN KEY (MaKH)
REFERENCES KHACH_HANG(MaKH)

-- 35. THONG_KE_COMMENT(NVThongKe) -> NHAN_VIEN(MaNV)
GO
ALTER TABLE THONG_KE_COMMENT
ADD CONSTRAINT FK_ThongKeCMT_NhanVienLap
FOREIGN KEY (NVThongKe)
REFERENCES NHAN_VIEN(MaNV)

-- 36. LICH_SU_TANG_QUA(NVLapLichSu) -> NHAN_VIEN(MaNV)
GO
ALTER TABLE LICH_SU_TANG_QUA
ADD CONSTRAINT FK_LichSuTangQua_NhanVienLap
FOREIGN KEY (NVLapLichSu)
REFERENCES NHAN_VIEN(MaNV)

-- 37. LICH_SU_TANG_QUA(MaKH) -> KHACH_HANG(MaKH)
GO
ALTER TABLE LICH_SU_TANG_QUA
ADD CONSTRAINT FK_LichSuTangQua_KhachHang
FOREIGN KEY (MaKH)
REFERENCES KHACH_HANG(MaKH)